version: "3"

services:
  web:
    container_name: "mime_viewer_app"
    build: .
    ports:
      - "80:80"
      - "8080:80"
      - "5173:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    tty: true
    stdin_open: true